[package]
name = "uwuc_mir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uwuc_base = { path = "../base" }
index_vec = "0.1"